/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package filechooser;
import classifier.Classifier;
import spam_window.SpamWindow;
import ham_window.HamWindow;
import java.io.File;
import javax.swing.JFileChooser;
import java.io.*;
import java.util.*;
/**
 *
 * @author vabs
 */
public class FileChooser extends javax.swing.JFrame {

    /**
     * Creates new form FileChooser
     */
    public FileChooser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fileName = new javax.swing.JTextField();
        fileAcceptButton = new javax.swing.JButton();
        cancelSelectedFile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 75));
        setSize(new java.awt.Dimension(600, 600));

        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("A://algo project//laststep//Images//new.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-1, -3, 600, 90);

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setText("SELECT FILE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(224, 249, 160, 60);

        fileName.setEditable(false);
        fileName.setBackground(new java.awt.Color(130, 184, 237));
        jPanel2.add(fileName);
        fileName.setBounds(200, 380, 300, 40);

        fileAcceptButton.setText("OK");
        fileAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileAcceptButtonActionPerformed(evt);
            }
        });
        jPanel2.add(fileAcceptButton);
        fileAcceptButton.setBounds(410, 540, 75, 25);

        cancelSelectedFile.setText("Cancel");
        cancelSelectedFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSelectedFileActionPerformed(evt);
            }
        });
        jPanel2.add(cancelSelectedFile);
        cancelSelectedFile.setBounds(500, 540, 75, 25);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("File Selected :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 380, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("A://algo project//laststep//Images//ppp.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-1, -3, 620, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("A://algo project//laststep//test data");
        int x=jfc.showOpenDialog(null);//showSaveDialog(null)
        if(x==JFileChooser.APPROVE_OPTION)
        {
            f=jfc.getSelectedFile();
            BufferedReader reader;
            String vv="";
            try{
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(f)));
            while ((vv = reader.readLine()) != null)
                System.out.println(vv);
            reader.close();
            }
            catch(Exception ex){}

            String s=jfc.getName(f);
            fileName.setText(s);

        }
        if(x==JFileChooser.CANCEL_OPTION)
        {
            System.out.println("cancel");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelSelectedFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSelectedFileActionPerformed
        // TODO add your handling code here:
        fileName.setText("");
        f = null;

    }//GEN-LAST:event_cancelSelectedFileActionPerformed

    private void fileAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileAcceptButtonActionPerformed
        // TODO add your handling code here:
        try{
           boolean checker = new Classifier().test(f);
           f=null;
           if(checker)
           	new SpamWindow("SPAM");
           else
           	new HamWindow("HAM");
        }
        catch(Exception ex){}
    }//GEN-LAST:event_fileAcceptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelSelectedFile;
    private javax.swing.JButton fileAcceptButton;
    private javax.swing.JTextField fileName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    public File f;
}
